### ISSUE TITLE
yarn install fails

### ISSUE THREAD

**Issue by satra** [ChildMindInstitute/mindlogger-app#45]
hopefully someone can update the instructions for building the app.

```
$ node -v
v11.3.0
$ yarn install
yarn install v1.12.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-native > metro-babel-register > @babel/plugin-proposal-optional-chaining@7.0.0-beta.47" has unmet peer dependency "@babel/core@7.0.0-beta.47".
warning "react-native > metro-babel-register > @babel/plugin-proposal-optional-chaining > @babel/plugin-syntax-optional-chaining@7.0.0-beta.47" has unmet peer dependency "@babel/core@7.0.0-beta.47".
warning " > react-native-audiowaveform@1.0.51" has incorrect peer dependency "react-native@^0.29.0".
warning " > react-native-progress-circle@2.0.0" has unmet peer dependency "prop-types@*".
warning " > react-native-sensors@2.4.2" has unmet peer dependency "prop-types@^15.6.0".
warning " > react-native-svg@6.1.3" has unmet peer dependency "prop-types@^15.5.7".
warning " > styled-components@4.1.1" has unmet peer dependency "react-dom@>= 16.3.0".
warning "metro-react-native-babel-preset > @babel/plugin-proposal-class-properties@7.1.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-proposal-nullish-coalescing-operator@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-proposal-object-rest-spread@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-proposal-optional-catch-binding@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-proposal-optional-chaining@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-arrow-functions@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-block-scoping@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-classes@7.1.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-computed-properties@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-destructuring@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-exponentiation-operator@7.1.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-flow-strip-types@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-for-of@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-function-name@7.1.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-literals@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-modules-commonjs@7.1.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-object-assign@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-parameters@7.1.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-react-display-name@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-react-jsx@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-react-jsx-source@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-regenerator@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-shorthand-properties@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-spread@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-sticky-regex@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-template-literals@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-typescript@7.1.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-unicode-regex@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-proposal-class-properties > @babel/plugin-syntax-class-properties@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-proposal-nullish-coalescing-operator > @babel/plugin-syntax-nullish-coalescing-operator@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-proposal-object-rest-spread > @babel/plugin-syntax-object-rest-spread@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-proposal-optional-catch-binding > @babel/plugin-syntax-optional-catch-binding@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-proposal-optional-chaining > @babel/plugin-syntax-optional-chaining@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-flow-strip-types > @babel/plugin-syntax-flow@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-react-jsx > @babel/plugin-syntax-jsx@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-typescript > @babel/plugin-syntax-typescript@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
[4/4] 📃  Building fresh packages...
[1/4] ⠐ fsevents
[-/4] ⠐ waiting...
[-/4] ⠐ waiting...
warning Error running install script for optional dependency: "/software/work/test_ml/mindlogger-app/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install
Arguments: 
Directory: /software/work/test_ml/mindlogger-app/node_modules/fsevents
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.36
node-pre-gyp info using node@11.3.0 | darwin | x64
node-pre-gyp info check checked for \"/software/work/test_ml/mindlogger-app/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node\" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v67-darwin-x64.tar.gz
node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v67-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v67-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@11.3.0 (node-v67 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v67-darwin-x64.tar.gz 
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v67-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@11.3.0 (node-v67 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http Connection closed while downloading tarball file 
gypgyp  infoinfo  it worked if it ends withit worked if it ends with ok
 ok
gyp infogyp using node-gyp@3.8.0
 infogyp  usinginfo  node-gyp@3.8.0
using node@11.3.0 | darwin | x64
gyp info using node@11.3.0 | darwin | x64
gypgyp  infoinfo ok 
 ok 
gypgyp info it worked if it ends with ok
 info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.3.0 | darwin | x64
gyp info using node-gyp@3.8.0
gyp info using node@11.3.0 | darwin | x64
gyp http GET https://nodejs.org/download/release/v11.3.0/node-v11.3.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v11.3.0/node-v11.3.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v11.3.0/node-v11.3.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v11.3.0/node-v11.3.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v11.3.0/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v11.3.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v11.3.0/SHASUMS256.txt
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/Cellar/node/11.3.0_1/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/software/work/test_ml/mindlogger-app/node_modules/fsevents/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/Cellar/node/11.3.0_1/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/satra/.node-gyp/11.3.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/satra/.node-gyp/11.3.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/Cellar/node/11.3.0_1/libexec/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/satra/.node-gyp/11.3.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/software/work/test_ml/mindlogger-app/node_modules/fsevents',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp http 200 https://nodejs.org/download/release/v11.3.0/SHASUMS256.txt
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/Cellar/node/11.3.0_1/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/software/work/test_ml/mindlogger-app/node_modules/fsevents/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/Cellar/node/11.3.0_1/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/satra/.node-gyp/11.3.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/satra/.node-gyp/11.3.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/Cellar/node/11.3.0_1/libexec/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/satra/.node-gyp/11.3.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/software/work/test_ml/mindlogger-app/node_modules/fsevents',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.3.0 | darwin | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.3.0 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from In file included from ../fsevents.cc:../fsevents.cc6::
In file included from ../../nan/nan.h6:
:In file included from 192../../nan/nan.h:
:../../nan/nan_maybe_43_inl.h192::
112../../nan/nan_maybe_43_inl.h::15112:: 15error::  no member named 'ForceSet' in 'v8::Object'
error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:198:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:337:28: warning: 'New' is deprecated: Use Isolate* version [-Wdeprecated-declarations]
  return v8::StringObject::New(value).As<v8::StringObject>();
                           ^
/Users/satra/.node-gyp/11.3.0/include/node/v8.h:5241:3: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED(\"Use Isolate* version\",
  ^
/Users/satra/.node-gyp/11.3.0/include/node/v8config.h:326:In file included from ../fsevents.cc:629::
 In file included from note../../nan/nan.h: expanded from macro 'V8_DEPRECATED'
:198:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:337  declarator __attribute__((deprecated(message)))
:                            ^
28: warning: 'New' is deprecated: Use Isolate* version [-Wdeprecated-declarations]
  return v8::StringObject::New(value).As<v8::StringObject>();
                           ^
/Users/satra/.node-gyp/11.3.0/include/node/v8.h:5241:3: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED(\"Use Isolate* version\",
  ^
/Users/satra/.node-gyp/11.3.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/satra/.node-gyp/11.3.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
^
/Users/satra/.node-gyp/11.3.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:849:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/satra/.node-gyp/11.3.0/include/node/node.h:164:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
^
/Users/satra/.node-gyp/11.3.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/satra/.node-gyp/11.3.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
In file included from ../fsevents.ccNODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
^:6:
../../nan/nan.h:864:
18:/Users/satra/.node-gyp/11.3.0/include/node/node.h:91 :20:warning:  'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]note
: expanded from macro 'NODE_DEPRECATED'
    return node::MakeCallback(
                 ^
/Users/satra/.node-gyp/11.3.0/include/node/node.h    __attribute__((deprecated(message))) declarator:
157                   ^:
1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
^
/Users/satra/.node-gyp/11.3.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:849:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/satra/.node-gyp/11.3.0/include/node/node.h:164:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
^
/Users/satra/.node-gyp/11.3.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:864:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/satra/.node-gyp/11.3.0/include/node/node.h:157:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
^
/Users/satra/.node-gyp/11.3.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:911:44: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
      v8::Local<v8::String> string = from->ToString();
                                           ^
/Users/satra/.node-gyp/11.3.0/include/node/v8.h:2548:10: note: 'ToString' has been explicitly marked deprecated here
  inline V8_DEPRECATED(\"Use maybe version\", Local<String> ToString() const);
         ^
/Users/satra/.node-gyp/11.3.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:911:44: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
In file included from ../fsevents.cc:6:
../../nan/nan.h:921:27:      v8::Local<v8::String> string = from->ToString();
                                           ^ 
warning: 'WriteUtf8' is deprecated: Use Isolate* version [-Wdeprecated-declarations]
/Users/satra/.node-gyp/11.3.0/include/node/v8.h:2548:10: note: 'ToString' has been explicitly marked deprecated here
        length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                          ^
/Users/satra/.node-gyp/11.3.0/include/node/v8.h:2753:3: note: 'WriteUtf8' has been explicitly marked deprecated here
  inline V8_DEPRECATED(\"Use maybe version\", Local<String> ToString() const);
         ^
/Users/satra/.node-gyp/11.3.0/include/node/v8config.h:  V8_DEPRECATED(\"Use Isolate* version\",
  ^
326:/Users/satra/.node-gyp/11.3.0/include/node/v8config.h:32629::29:  notenote: expanded from macro 'V8_DEPRECATED'
: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:921:27: warning: 'WriteUtf8' is deprecated: Use Isolate* version [-Wdeprecated-declarations]
        length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                          ^
/Users/satra/.node-gyp/11.3.0/include/node/v8.h:2753:3: note: 'WriteUtf8' has been explicitly marked deprecated here
  V8_DEPRECATED(\"Use Isolate* version\",
  ^
/Users/satra/.node-gyp/11.3.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/satra/.node-gyp/11.3.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
^
/Users/satra/.node-gyp/11.3.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/satra/.node-gyp/11.3.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
^
/Users/satra/.node-gyp/11.3.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
7 warnings and 1 error generated.
7 warnings and 1 error generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/11.3.0_1/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gypgyp ERR!  stackERR!     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
 stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/11.3.0_1/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR!gyp stack      at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
ERR! System Darwin 18.2.0
gyp ERR! System Darwin 18.2.0
gyp ERR! commandgyp \"/usr/local/Cellar/node/11.3.0_1/bin/node\" \"/usr/local/Cellar/node/11.3.0_1/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/software/work/test_ml/mindlogger-app/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/software/work/test_ml/mindlogger-app/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64\"
 ERR! commandgyp \"/usr/local/Cellar/node/11.3.0_1/bin/node\" \"/usr/local/Cellar/node/11.3.0_1/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/software/work/test_ml/mindlogger-app/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/software/work/test_ml/mindlogger-app/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64\"
 ERR!gyp  ERR! cwdcwd /software/work/test_ml/mindlogger-app/node_modules/fsevents
 /software/work/test_ml/mindlogger-app/node_modules/fsevents
gyp ERR!gyp  ERR! node -vnode -v v11.3.0
 v11.3.0
gypgyp ERR!  node-gyp -vERR! v3.8.0
 gyp node-gyp -vERR! v3.8.0
 gyp not okERR! 
 not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp build --fallback-to-build --module=/software/work/test_ml/mindlogger-app/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node --module_name=fse --module_path=/software/work/test_ml/mindlogger-app/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/software/work/test_ml/mindlogger-app/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command \"/usr/local/Cellar/node/11.3.0_1/bin/node\" \"/software/work/test_ml/mindlogger-app/node_modules/fsevents/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /software/work/test_ml/mindlogger-app/node_modules/fsevents
node-pre-gyp ERR! node -v v11.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
Failed to execute 'node-gyp build --fallback-to-build --module=/software/work/test_ml/mindlogger-app/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node --module✨  Done in 109.18s.

```

**Comment by shnizzedy** [comment]
I'm not sure if this requirement is the same for the app as the admin panel, but I'm guessing so based on the same node-gyp error. Try [using Node v10.11.0 instead of v11.3.0](https://github.com/ChildMindInstitute/mindlogger-app-admin-panel/blob/146be2e1622fc7e6e69fd988e4fe157933256b8d/README.md#all-installations).

**Comment by satra** [comment]
thanks @shnizzedy  - will try.

**Comment by binarybottle** [comment]
Super old issue, and we're building fine now within bitrise.
